name: Integration tests

on: [push, pull_request, pull_request_target]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: woorule

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.1

      - name: WooCommerce Checkout
        uses: actions/checkout@v2
        with:
          repository: woocommerce/woocommerce
          ref: 6.2.0
          path: woocommerce

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension: intl, mbstring, json, bcmath
          coverage: xdebug
          tools: composer, php-cs-fixer, phpunit:7.5.20, phpcpd, phpmd

      - name: Set up MySQL
        run: sudo systemctl start mysql.service

      - name: Build the plugin package
        run: |
          cd $GITHUB_WORKSPACE/woorule
          composer install
          zip -q -r /tmp/woorule.zip ./

      - name: Build WooCommerce package
        run: |
          cd $GITHUB_WORKSPACE/woocommerce/plugins/woocommerce
          composer install
          #npm install --g pnpm
          pnpm install
          #pnpm nx build woocommerce
          pnpm nx composer-install woocommerce
          zip -q -r /tmp/woocommerce.zip ./

      - name: Build WordPress Test Enviroment
        run: |
          cd $GITHUB_WORKSPACE/woocommerce/plugins/woocommerce
          bash tests/bin/install.sh woocommerce_test root 'root' localhost latest
          cd /tmp/wordpress
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar core config --dbname=woocommerce_test --dbuser=root --dbpass='root' --dbhost=localhost --dbprefix=wp_
          php wp-cli.phar core install --url="http://localhost:8080" --title="Example" --admin_user=admin --admin_password=password --admin_email=info@example.com --path=/tmp/wordpress --skip-email
          php wp-cli.phar plugin install /tmp/woocommerce.zip --activate
          php wp-cli.phar plugin install /tmp/woorule.zip --activate

      - name: Run tests
        env:
          RULE_API_KEY: ${{ secrets.RULE_API_KEY }}
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_RUN_CORE_TESTS: 1
        run: |
          cd $GITHUB_WORKSPACE/woorule
          WOOCOMMERCE_DIR=$GITHUB_WORKSPACE/woocommerce/plugins/woocommerce $GITHUB_WORKSPACE/woocommerce/plugins/woocommerce/vendor/phpunit/phpunit/phpunit --configuration=./tests/phpunit.xml --bootstrap=./tests/bootstrap.php --coverage-clover=coverage.xml

      - name: Upload code coverage report to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
