name: Code verification

on: [push, pull_request, pull_request_target]

jobs:
  test:
    name: Code verification
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' || github.event_name == 'push')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: woorule

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          extensions: intl, mbstring, json, bcmath
          tools: composer:v1

      - name: Run PHPCS inspection
        run: |
          cd $GITHUB_WORKSPACE/woorule
          composer install
          ./vendor/bin/phpcs --standard=WordPress-Core --report=code --ignore=.github,tests,.wordpress-org,assets/*.js,assets/*.css,vendor --runtime-set ignore_warnings_on_exit true ./

      - name: Run PHPMD inspection
        run: |
          cd $GITHUB_WORKSPACE/woorule
          composer install
          ./vendor/bin/phpmd ./ text cleancode,codesize,controversial,design,naming,unusedcode --exclude .github,tests,vendor
